* Lieberman 2009 在算 intra Pearson matrix 前會先把 O/E matrix 的所有 0 rows 和 0 columns 移除（根據檔案儲存方式也有可能是 NaN rows, NaN columns）
* Interchromosomal contacts 應該需要把 chr1 - chrY 全部串接起來成為方陣，再算 Peason matrix (看 2009 Paper Fig.2.B) ，這個等 Intra 驗證完再做

In [1]:
!pwd

/home/jordan990301/Projects/HiC-PC1_Approximation/test


In [2]:
import numpy as np
import pandas as pd
from copy import deepcopy
np.set_printoptions(suppress=True)

# pd.set_option('display.max_rows', None)
# pd.set_option('display.max_columns', None)

path = "/home/jordan990301/Projects/HiC-PC1_Approximation/data/Lieberman_Aiden-datasets/heatmaps"

In [7]:
oe_all = None
chrom_list = ['1', '2', '3']

for i in chrom_list:
    oe_row = pd.read_table(f"{path}/HIC_gm06690_chr{i}_chr1_1000000_obsexp.txt", index_col=0, header=1, sep="\t")
    oe_row.pop(oe_row.columns[-1])
    for j in chrom_list:
        if j == '1':
            continue
        else:
            oe_element = pd.read_table(f"{path}/HIC_gm06690_chr{i}_chr{j}_1000000_obsexp.txt", index_col=0, header=1, sep="\t")
            oe_element.pop(oe_element.columns[-1])
            oe_row = pd.concat([oe_row, oe_element], axis=1)

    oe_all = pd.concat([oe_all, oe_row])

display(oe_all)
display(oe_row)

# # remove 0 rows and 0 columns
# # https://stackoverflow.com/questions/11188364/remove-zero-lines-2-d-numpy-array
# oe_np = oe_np[~np.all(oe_np == 0, axis=1)]
# oe_np = oe_np[:, ~np.all(oe_np == 0, axis=0)]

# # zero means
# # oe_np = oe_np - oe_np.mean(axis=1, keepdims=True)


FileNotFoundError: [Errno 2] No such file or directory: '/home/jordan990301/Projects/HiC-PC1_Approximation/data/Lieberman_Aiden-datasets/heatmaps/HIC_gm06690_chr2_chr1_1000000_obsexp.txt'

In [81]:
pearson_df = pd.read_table(f"{path}/HIC_gm06690_chr1_chr10_1000000_pearson.txt", index_col=0, header=1, sep="\t")
pearson_df.pop(pearson_df.columns[-1])
display(pearson_df)

HIC_bin1|hg18|chr10:1-999999  \
HIC_bin1|hg18|chr1:1-999999                                   0.141275   
HIC_bin2|hg18|chr1:1000000-1999999                            0.200796   
HIC_bin3|hg18|chr1:2000000-2999999                            0.205439   
HIC_bin4|hg18|chr1:3000000-3999999                            0.175861   
HIC_bin5|hg18|chr1:4000000-4999999                            0.046572   
...                                                                ...   
HIC_bin244|hg18|chr1:243000000-243999999                     -0.039856   
HIC_bin245|hg18|chr1:244000000-244999999                     -0.048387   
HIC_bin246|hg18|chr1:245000000-245999999                     -0.074084   
HIC_bin247|hg18|chr1:246000000-246999999                     -0.016460   
HIC_bin248|hg18|chr1:247000000-247249718                      0.000000   

                                          HIC_bin2|hg18|chr10:1000000-1999999  \
HIC_bin1|hg18|chr1:1-999999                                          0.031301   
HIC_bin2|hg18|chr1:1000000-1999999                                   0.068667   
HIC_bin3|hg18|chr1:2000000-2999999                                   0.104754   
HIC_bin4|hg18|chr1:3000000-3999999                                   0.109153   
HIC_bin5|hg18|chr1:4000000-4999999                                   0.091548   
...                                                                       ...   
HIC_bin244|hg18|chr1:243000000-243999999                            -0.055973   
HIC_bin245|hg18|chr1:244000000-244999999                            -0.027753   
HIC_bin246|hg18|chr1:245000000-245999999                            -0.065769   
HIC_bin247|hg18|chr1:246000000-246999999                            -0.025228   
HIC_bin248|hg18|chr1:247000000-247249718                             0.000000   

                                          HIC_bin3|hg18|chr10:2000000-2999999  \
HIC_bin1|hg18|chr1:1-999999                                         -0.017621   
HIC_bin2|hg18|chr1:1000000-1999999                                  -0.038317   
HIC_bin3|hg18|chr1:2000000-2999999                                   0.034800   
HIC_bin4|hg18|chr1:3000000-3999999                                   0.052853   
HIC_bin5|hg18|chr1:4000000-4999999                                   0.113884   
...                                                                       ...   
HIC_bin244|hg18|chr1:243000000-243999999                            -0.020706   
HIC_bin245|hg18|chr1:244000000-244999999                             0.020651   
HIC_bin246|hg18|chr1:245000000-245999999                            -0.021705   
HIC_bin247|hg18|chr1:246000000-246999999                             0.021343   
HIC_bin248|hg18|chr1:247000000-247249718                             0.000000   

                                          HIC_bin4|hg18|chr10:3000000-3999999  \
HIC_bin1|hg18|chr1:1-999999                                          0.031787   
HIC_bin2|hg18|chr1:1000000-1999999                                   0.048354   
HIC_bin3|hg18|chr1:2000000-2999999                                   0.092157   
HIC_bin4|hg18|chr1:3000000-3999999                                   0.099251   
HIC_bin5|hg18|chr1:4000000-4999999                                   0.077068   
...                                                                       ...   
HIC_bin244|hg18|chr1:243000000-243999999                            -0.030659   
HIC_bin245|hg18|chr1:244000000-244999999                            -0.058896   
HIC_bin246|hg18|chr1:245000000-245999999                            -0.061532   
HIC_bin247|hg18|chr1:246000000-246999999                            -0.065691   
HIC_bin248|hg18|chr1:247000000-247249718                             0.000000   

                                          HIC_bin5|hg18|chr10:4000000-4999999  \
HIC_bin1|hg18|chr1:1-999999                                         -0.035810   
HIC_bin2|hg18|chr1:1000000-1999999                                  -0.0

In [82]:
# https://stackoverflow.com/questions/11188364/remove-zero-lines-2-d-numpy-array

import numpy as np
import pandas as pd

a_df = pd.DataFrame({'a':[0,0,0,1], 'b':[0,1,0,1], 'c':[0,0,0,0]})
a_np = a_df.values

print(a_np, '\n')
a_np = a_np[~np.all(a_np == 0, axis=1)]
print(a_np, '\n')
a_np = a_np[:, ~np.all(a_np == 0, axis=0)]
print(a_np, '\n')

[[0 0 0]
 [0 1 0]
 [0 0 0]
 [1 1 0]] 

[[0 1 0]
 [1 1 0]] 

[[0 1]
 [1 1]] 

