* Lieberman 2009 在算 intra Pearson matrix 前會先把 O/E matrix 的所有 0 rows 和 0 columns 移除（根據檔案儲存方式也有可能是 NaN rows, NaN columns）

In [1]:
!pwd

/home/jordan990301/Projects/HiC-PC1_Approximation/test


In [2]:
import numpy as np
import pandas as pd
from copy import deepcopy
np.set_printoptions(suppress=True)

# pd.set_option('display.max_rows', None)
# pd.set_option('display.max_columns', None)

path = "/home/jordan990301/Projects/HiC-PC1_Approximation/data/Lieberman_Aiden-datasets/heatmaps"

In [3]:
oe = pd.read_table(f"{path}/HIC_gm06690_chr10_chr10_1000000_obsexp.txt", index_col=0, header=1, sep="\t")
oe.pop(oe.columns[-1])

oe_np = oe.values
# remove 0 rows and 0 columns
# https://stackoverflow.com/questions/11188364/remove-zero-lines-2-d-numpy-array
oe_np = oe_np[~np.all(oe_np == 0, axis=1)]
oe_np = oe_np[:, ~np.all(oe_np == 0, axis=0)]

# zero means
oe_np = oe_np - oe_np.mean(axis=1, keepdims=True)

n = len(oe_np)
# y_np = oe_np.T / np.sqrt(n)
y_np = oe_np.T / np.sqrt(n - 1)
cov_oe_np = np.matmul(y_np.T, y_np)

# print(cov_oe_np, '\n')
# print(np.cov(oe_np))

corr_oe_np = np.empty(shape=(n, n))
corr_oe_np.fill(0)

for i in range(n):
    for j in range(n):
        corr_oe_np[i][j] = cov_oe_np[i][j] / np.sqrt(cov_oe_np[i][i] * cov_oe_np[j][j])

display(corr_oe_np)
np.corrcoef(oe_np)

array([[1.        , 0.62017141, 0.49181362, ..., 0.4925558 , 0.59291721,
        0.54164249],
       [0.62017141, 1.        , 0.66661132, ..., 0.56958098, 0.67411149,
        0.64363884],
       [0.49181362, 0.66661132, 1.        , ..., 0.60437888, 0.54407688,
        0.54857453],
       ...,
       [0.4925558 , 0.56958098, 0.60437888, ..., 1.        , 0.88268867,
        0.89594578],
       [0.59291721, 0.67411149, 0.54407688, ..., 0.88268867, 1.        ,
        0.90792354],
       [0.54164249, 0.64363884, 0.54857453, ..., 0.89594578, 0.90792354,
        1.        ]])

array([[1.        , 0.62017141, 0.49181362, ..., 0.4925558 , 0.59291721,
        0.54164249],
       [0.62017141, 1.        , 0.66661132, ..., 0.56958098, 0.67411149,
        0.64363884],
       [0.49181362, 0.66661132, 1.        , ..., 0.60437888, 0.54407688,
        0.54857453],
       ...,
       [0.4925558 , 0.56958098, 0.60437888, ..., 1.        , 0.88268867,
        0.89594578],
       [0.59291721, 0.67411149, 0.54407688, ..., 0.88268867, 1.        ,
        0.90792354],
       [0.54164249, 0.64363884, 0.54857453, ..., 0.89594578, 0.90792354,
        1.        ]])

In [4]:
pearson_df = pd.read_table(f"{path}/HIC_gm06690_chr10_chr10_1000000_pearson.txt", index_col=0, header=1, sep="\t")
pearson_df.pop(pearson_df.columns[-1])
display(pearson_df)

HIC_bin1|hg18|chr10:1-999999  \
HIC_bin1|hg18|chr10:1-999999                                   1.000000   
HIC_bin2|hg18|chr10:1000000-1999999                            0.620171   
HIC_bin3|hg18|chr10:2000000-2999999                            0.491814   
HIC_bin4|hg18|chr10:3000000-3999999                            0.546186   
HIC_bin5|hg18|chr10:4000000-4999999                            0.322324   
...                                                                 ...   
HIC_bin132|hg18|chr10:131000000-131999999                      0.461570   
HIC_bin133|hg18|chr10:132000000-132999999                      0.436100   
HIC_bin134|hg18|chr10:133000000-133999999                      0.492556   
HIC_bin135|hg18|chr10:134000000-134999999                      0.592917   
HIC_bin136|hg18|chr10:135000000-135374736                      0.541642   

                                           HIC_bin2|hg18|chr10:1000000-1999999  \
HIC_bin1|hg18|chr10:1-999999                                          0.620171   
HIC_bin2|hg18|chr10:1000000-1999999                                   1.000000   
HIC_bin3|hg18|chr10:2000000-2999999                                   0.666611   
HIC_bin4|hg18|chr10:3000000-3999999                                   0.637837   
HIC_bin5|hg18|chr10:4000000-4999999                                   0.451535   
...                                                                        ...   
HIC_bin132|hg18|chr10:131000000-131999999                             0.574289   
HIC_bin133|hg18|chr10:132000000-132999999                             0.544274   
HIC_bin134|hg18|chr10:133000000-133999999                             0.569581   
HIC_bin135|hg18|chr10:134000000-134999999                             0.674111   
HIC_bin136|hg18|chr10:135000000-135374736                             0.643639   

                                           HIC_bin3|hg18|chr10:2000000-2999999  \
HIC_bin1|hg18|chr10:1-999999                                          0.491814   
HIC_bin2|hg18|chr10:1000000-1999999                                   0.666611   
HIC_bin3|hg18|chr10:2000000-2999999                                   1.000000   
HIC_bin4|hg18|chr10:3000000-3999999                                   0.522435   
HIC_bin5|hg18|chr10:4000000-4999999                                   0.500241   
...                                                                        ...   
HIC_bin132|hg18|chr10:131000000-131999999                             0.553098   
HIC_bin133|hg18|chr10:132000000-132999999                             0.575181   
HIC_bin134|hg18|chr10:133000000-133999999                             0.604379   
HIC_bin135|hg18|chr10:134000000-134999999                             0.544077   
HIC_bin136|hg18|chr10:135000000-135374736                             0.548575   

                                           HIC_bin4|hg18|chr10:3000000-3999999  \
HIC_bin1|hg18|chr10:1-999999                                          0.546186   
HIC_bin2|hg18|chr10:1000000-1999999                                   0.637837   
HIC_bin3|hg18|chr10:2000000-2999999                                   0.522435   
HIC_bin4|hg18|chr10:3000000-3999999                                   1.000000   
HIC_bin5|hg18|chr10:4000000-4999999                                   0.361358   
...                                                                        ...   
HIC_bin132|hg18|chr10:131000000-131999999                             0.472182   
HIC_bin133|hg18|chr10:132000000-132999999                             0.482784   
HIC_bin134|hg18|chr10:133000000-133999999                             0.494242   
HIC_bin135|hg18|chr10:134000000-134999999                             0.558266   
HIC_bin136|hg18|chr10:135000000-135374736                             0.579293   

                                           HIC_bin5|hg18|chr10:4000000-4999999  \
HIC_bin1|hg18|chr10:1-999999                                          0.322324   
HIC_bin2|hg18|chr10:100

In [5]:
# https://stackoverflow.com/questions/11188364/remove-zero-lines-2-d-numpy-array

import numpy as np
import pandas as pd

a_df = pd.DataFrame({'a':[0,0,0,1], 'b':[0,1,0,1], 'c':[0,0,0,0]})
a_np = a_df.values

print(a_np, '\n')
a_np = a_np[~np.all(a_np == 0, axis=1)]
print(a_np, '\n')
a_np = a_np[:, ~np.all(a_np == 0, axis=0)]
print(a_np, '\n')

[[0 0 0]
 [0 1 0]
 [0 0 0]
 [1 1 0]] 

[[0 1 0]
 [1 1 0]] 

[[0 1]
 [1 1]] 

