In [17]:
import numpy as np
from scipy import sparse

In [18]:
row = np.array([0, 0, 1, 2, 2, 2])
col = np.array([0, 2, 2, 0, 1, 2])
data = np.array([1, 2, 3, 4, 5, 6])

A = sparse.csr_array((data, (row, col)), shape=(3, 3)).toarray()
A

array([[1, 0, 2],
       [0, 0, 3],
       [4, 5, 6]])

In [19]:
# A.dot(A[0])
A @ A[0]

array([ 5,  6, 16])

In [20]:
B = np.array([[1,2,0],[0,0,3],[1,0,4]])
sB = sparse.csr_matrix(B)

print(B, '\n')
print(sB, '\n')

[[1 2 0]
 [0 0 3]
 [1 0 4]] 

  (0, 0)	1
  (0, 1)	2
  (1, 2)	3
  (2, 0)	1
  (2, 2)	4 



In [21]:
row = np.array([0, 0, 1, 2, 2, 2])
col = np.array([0, 2, 2, 0, 1, 2])
data = np.array([1, 2, 3, 4, 5, 6])
sA = sparse.csr_matrix((data, (row, col)), shape=(3, 3))

print(sA.toarray())

[[1 0 2]
 [0 0 3]
 [4 5 6]]


In [22]:
sA[0].toarray() - sA[0].mean()

array([[ 0., -1.,  1.]])

In [23]:
B = np.array([[1, 0, 2], [0, 0, 3], [4, 5, 6]])
np.std(B[0])

0.816496580927726

In [31]:
import numpy as np
from scipy.sparse import csr_matrix

# Diagonal elements
diagonal_data = np.array([1, 2, 3])  # Replace with your desired diagonal values

# Create the CSR matrix (assuming a square matrix)
diagonal_matrix = csr_matrix((diagonal_data, np.arange(len(diagonal_data)), np.arange(len(diagonal_data) + 1)),
                            shape=(len(diagonal_data), len(diagonal_data)))

# Print the sparse matrix (optional)
print(diagonal_matrix.toarray())


[[1 0 0]
 [0 2 0]
 [0 0 3]]
