In [25]:
import numpy as np
from copy import deepcopy

a = np.array([[1, 0, 0, 0, 0], [0, 1, 0, 3, 0], [4, 5, 0, 7, 0], [0, 0, 0, 1, 0], [8, 9, 0, 11, 0]])
a = np.corrcoef(a)

a[2] = 0
a[4] = 0
for i in a:
    i[2] = 0
    i[4] = 0

print(a, '\n')

a_diag = np.diag(a)
a_diag_pos = a_diag > 0.999

print(a_diag_pos, '\n')

ixgrid = np.ix_(a_diag_pos, a_diag_pos)
print(a[ixgrid], '\n')

print(a[ixgrid].mean(axis=1, keepdims=True), '\n')

a[ixgrid] -= a[ixgrid].mean(axis=1, keepdims=True)
print(a)

[[ 1.         -0.34299717  0.         -0.25        0.        ]
 [-0.34299717  1.          0.          0.94324222  0.        ]
 [ 0.          0.          0.          0.          0.        ]
 [-0.25        0.94324222  0.          1.          0.        ]
 [ 0.          0.          0.          0.          0.        ]] 

[ True  True False  True False] 

[[ 1.         -0.34299717 -0.25      ]
 [-0.34299717  1.          0.94324222]
 [-0.25        0.94324222  1.        ]] 

[[0.13566761]
 [0.53341502]
 [0.56441407]] 

[[ 0.86433239 -0.47866478  0.         -0.38566761  0.        ]
 [-0.87641219  0.46658498  0.          0.4098272   0.        ]
 [ 0.          0.          0.          0.          0.        ]
 [-0.81441407  0.37882815  0.          0.43558593  0.        ]
 [ 0.          0.          0.          0.          0.        ]]


In [26]:
# a = a[~np.all(a == 0, axis=1)]
# a = a[:, ~np.all(a == 0, axis=0)]
# print(len(a))
# print(np.mean(a[0]))
# print(np.mean(a[1]))
# print(np.mean(a[2]))

In [27]:
b = deepcopy(a)
print(b, '\n')
print(b[ixgrid], '\n')
b[ixgrid] = np.cov(b[ixgrid])
print(b, '\n')

[[ 0.86433239 -0.47866478  0.         -0.38566761  0.        ]
 [-0.87641219  0.46658498  0.          0.4098272   0.        ]
 [ 0.          0.          0.          0.          0.        ]
 [-0.81441407  0.37882815  0.          0.43558593  0.        ]
 [ 0.          0.          0.          0.          0.        ]] 

[[ 0.86433239 -0.47866478 -0.38566761]
 [-0.87641219  0.46658498  0.4098272 ]
 [-0.81441407  0.37882815  0.43558593]] 

[[ 0.56246498 -0.56945316  0.         -0.52662377  0.        ]
 [-0.56945316  0.5768791   0.          0.53451645  0.        ]
 [ 0.          0.          0.          0.          0.        ]
 [-0.52662377  0.53451645  0.          0.49825807  0.        ]
 [ 0.          0.          0.          0.          0.        ]] 



In [28]:
a = a[~np.all(a == 0, axis=1)]
a = a[:, ~np.all(a == 0, axis=0)]
print(np.cov(a))

[[ 0.56246498 -0.56945316 -0.52662377]
 [-0.56945316  0.5768791   0.53451645]
 [-0.52662377  0.53451645  0.49825807]]


True